blank_issues_enabled: false
contact_links:
  - name: Development Documentation
    url: https://github.com/Warm7yry/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Read the development guide for technical information about the system